[tool.poetry]
name = "reinforest_with_yukky"
version = "0.1.0"
description = ""
<<<<<<< HEAD
authors = ["Your Name <you@example.com>"]
=======
authors = [""]
>>>>>>> d4c39c7af715cf9ea708e56ac7db0f5eb4de69c4

[tool.poetry.dependencies]
python = "^3.8"
IPython = "^7.15.0"
matplotlib = "^3.2.1"
logzero = "^1.5.0"
jupyter = "^1.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
<<<<<<< HEAD
build-backend = "poetry.masonry.api"
=======
build-backend = "poetry.masonry.api"
>>>>>>> d4c39c7af715cf9ea708e56ac7db0f5eb4de69c4
